#!/bin/sh

exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'My OS' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'my_os_single_shell' {

	echo    'My OS: Loading Linux 5.15.0-57-generic ...'
	linux   /boot/vmlinuz.old root=UUID=d90c5e60-d806-4fb4-824f-b943cac389e3 ro init=/bin/bash
	
	echo    'My OS: Loading initial ramdisk ...'
	initrd  /boot/initrd.img.old
}

