#!/bin/sh

menuentry 'My OS' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'my_os_single_shell' {
	#recordfail
	#load_video
	insmod gzio
	insmod part_gpt
	insmod ext2
	#set root='hd0,gpt3'
	#if [ x$feature_platform_search_hint = xy ]; then
	#	search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  d90c5e60-d806-4fb4-824f-b943cac389e3
	#else
	#	search --no-floppy --fs-uuid --set=root d90c5e60-d806-4fb4-824f-b943cac389e3
	#fi

	echo    'My OS: Loading Linux 5.15.0-57-generic ...'
	linux   /boot/vmlinuz-5.15.0-57-generic root=UUID=d90c5e60-d806-4fb4-824f-b943cac389e3 ro init=/bin/bash
	
	echo    'My OS: Loading initial ramdisk ...'
	initrd  /boot/initrd.img-5.15.0-57-generic
}
