version: "3.9"
services:
  postgres:
    image: postgres:14.6
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_PASSWORD: "1q2w3e"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./tables:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
